### ISSUE TITLE
Do not handle browser focus if `autofocus === false`

### ISSUE THREAD

**Issue by aldo-roman** [theKashey/react-focus-lock#113]
**Current behaviour**
Currently, if `autofocus` is `false`, the library removes focus on active element and focuses back to `body`.

This makes it impossible for the app to handle the focus restoring manually, as suggested in docs.

https://github.com/theKashey/react-focus-lock/blob/9236327421ce83d4b08b87b3c9b8838af5c83ce6/src/Trap.js#L102

**Expected behaviour**
Handle focus behaviour only when `autofocus === true`, and do nothing when `autofocus === false`

**Comment by theKashey** [comment]
The current logic is more about initial focusing than restoring. Could you share you particular use case to let me better understand the situation? 
Probably a new option might do a better job here.

**Comment by aldo-roman** [comment]
I need to do manual focus restore. When opening the modal, the library changes the focus to `body`, so it is not possible to find which element triggered the action.

As a dev, one would expect that setting `autoFocus` to false will not have any side effect from the library. In this case, it is blurring the active element and moving focus to body.

**Comment by theKashey** [comment]
Yep, so the logic is - if nothing "inside" should have a focus initially - then __nothing__ should be focused at all.
There is no way it can keep something focused after activation.

What you want to do is not related to the autofocus behavior - you want to do something _instead_ of lock. And in your particular case you need to act on lock activation - for the given example (remember return-to element) FocusLock itself uses `onActivation` callback, and you can do the same.
It is executed just before lock become active, before any other action - https://github.com/theKashey/react-focus-lock/blob/master/src/Trap.js#L213

**Comment by theKashey** [comment]
See https://github.com/theKashey/react-focus-lock/blob/master/interfaces.d.ts#L59

**Comment by aldo-roman** [comment]
Thanks. Using the activation hooks and some effects made it possible to workaround this issue.

> if nothing "inside" should have a focus initially - then nothing should be focused at all.

On the other hand, that's where we don't agree.  
The [W3 Authoring practices for dialogs](https://www.w3.org/TR/wai-aria-practices-1.1/#keyboard-interaction-7) say:  
> In all circumstances, focus moves to an element contained in the dialog

This is the reason why we are trying to manually handle the focus. Either an existing focusable element or the modal heading (in our implementation, there is always a heading) should be in focus. Moving the focus to body, or blurring it at all, contradicts this Authoring practices guide.

Finally, all `autofocus` properties in HTML perform side effects only when set to `true`, and leave the focus unhandled when set to `false`. Handling the focus when `autofocus` is `false` is a source of confusion.

**Comment by theKashey** [comment]
focus-lock could be used not only for modals, and for modals it would be just not enough.

There is only one rule -> user intention follows the focus. So focus controls what text-to-speach engines would _tell_ the user. And the best way to check how it works - test it. The majority of dialogs would tell you "Close", due to autofocus on close button.

> Personally I would not recommend blindly following W3 recommendations as long as the factual implementation of speech-to-tech engines is also not compatible with those specifications as well. And examples W3 provides for dialogs are not _factually_ correct.

Today the best solution is to add `tabindex=-1` to the modal itself, and focus it, and as a result text-to-speach engine will start reading modal content, not the action without any brief description. In any other case, with some `aria-groups`, `described-by`, `controls`/`owns` that might not happen at all - it would be just "close, button", "inside a dialog", "what dialog?!"

👉 In all circumstances, focus __moves to a dialog element__, and is contained inside after.

To move focus where it should be - use `MoveFocusInside` component.

**Comment by theKashey** [comment]
Latest versions allows a full manual control over "restoring focus" (`returnFocus` as a function)
That should be enough to handle all possible edge cases.
