### ISSUE TITLE
Cannot select text when focus lock is enabled

### ISSUE THREAD

**Issue by sachetsharma1** [theKashey/react-focus-lock#124]
Focus lock is preventing the text selection and focus goes back to first focusable element when you click anywhere inside the container. This seems to be same as https://github.com/theKashey/react-focus-lock/issues/10 which has resurfaced in the new version. 

I have tried explicitly setting the persistentFocus=false it has no effect.

**Comment by theKashey** [comment]
`persistentFocus` is working only with focus on the `document.body`, if you have any other focusable element in between - it will be focused and FocusLock will trigger.

It might act like - https://github.com/theKashey/react-focus-lock/issues/79 - in Safari you can click "through" the button.

Possible solutions: 
- use [while-list](https://github.com/theKashey/react-focus-lock/blob/master/interfaces.d.ts#L80) to "ignore" elements which a focus

**Comment by sachetsharma1** [comment]
I have tried using whitelist and shards to fix the problem but I still see the issue. I found this codesandbox that demonstrates the similar problem but in a different setup.

https://codesandbox.io/s/react-focus-lock-c0rrv?file=/index.js

**Comment by mrudowski** [comment]
[sachetsharma1](https://github.com/sachetsharma1)
very good example

still valid in 2022 in Chrome
in Firefox (on MacOs) we can select text but in wild way - from end of text line to cursor

**Comment by theKashey** [comment]
if there is an `tabindex={-1}`(better that 0, but 0 would also work) element __within__ the lock you should be able to select any text inside it with no issue. Because focus would be within the lock.

If there is no such element - text selection would work __only__ if there is no focusable element in between `Lock` and the `body`. Because focusing body is implicitly allowed.
