### ISSUE TITLE
Reverse trap

### ISSUE THREAD

**Issue by eduardodallmann** [theKashey/react-focus-lock#133]
Hello, how to prevent the elements inside from getting the focus? Allow all elements of the page to receive focus, except for what is inside the component. Basically how to reverse the focus trap?
Like this: https://www.starbucks.com/developer/pattern-library/components/prevent-focus/

**Comment by theKashey** [comment]
Sounds like a little different use case. From the starbucks: _this time they have one major A11y limitation: They don't prevent screen readers from navigating to items that are tabbable outside the focus trap/loop._ - that's why other packages, like [react-focus-on](https://github.com/theKashey/react-focus-on) and [aria-hidden](https://github.com/theKashey/aria-hidden) were created - to "hide" everything but the active lock.

However all these libraries (and this one) are designed to keep only "location" and _block_ the rest, while you are asking for 🤷‍♂️ reverse logic :)
Technically you can listen to `onFocus` inside some specific area you don't want to be focused and on focus use logic exposed from [focus-lock](https://github.com/theKashey/focus-lock) to calculate the next focusable element (like the next elements which shall be focused _if_ the some area is _disabled_. However, I could not give you any example.

Let me think about how this can be properly addressed.

**Comment by tamlyn** [comment]
I'm looking for this too. My use case is a multi step form where one section is disabled until the previous section is complete.

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/115310/155113836-8fb3302c-bec9-4a7d-930a-d4e9ed051f7e.png">

**Comment by theKashey** [comment]
That's another very good use case. But probably a little complicated as well - one should not only disable focus, but hide that area from screen readers as well as disable pointer events.
Everything in "reverse"
