### ISSUE TITLE
Focus lock is not working on TalkBack + Chrome

### ISSUE THREAD

**Issue by chemoish** [theKashey/react-focus-lock#137]
**On an Android (Chrome: 88.0.4324.141) device execute the following:**

![image](https://user-images.githubusercontent.com/549319/106955785-8f732300-66ea-11eb-9b3f-7216ff04c9df.png)

1. Open https://codesandbox.io/s/5wmrwlvxv4
2. Press run application
3. Press and hold volume buttons for 3 seconds
4. Press "!ACTIVATE THE TRAP!"
5. Swipe

**Notice the following:**

1. Focus lock **does not** work
2. Focus disappears when focusing on an element with `tabindex="0"` (i.e. Swiping after you are focused on "All your focus belongs to us!" will cause the focus to disappear when it arrives on the next element)

Is this a known issue?

**Comment by theKashey** [comment]
> Is this a known issue?

Yes and no. 
- this is a first time I hear about "TalkBack". Still not sure what it is
- with other assistive tools active (any text-to-speech) focus lock usually not working, as long as you "select" some text to be "said", not "focus" it
- in order to disallow any interactions outside of a Focus you might be required to use https://github.com/theKashey/aria-hidden - it will literally hide everything except the lock from screen readers.
- see https://github.com/theKashey/react-focus-on for details

**Comment by chemoish** [comment]
Thanks, I will keep this in mind during future testing.

FWIW, https://support.google.com/accessibility/android/answer/6283677?hl=en.

**Comment by theKashey** [comment]
😅 so basically a _VoiceOver_ - some sort of screen reader. Then usual rules applies and `aria-hidden` should be a solution.

**Comment by chemoish** [comment]
Does this mean that Aria hidden should be applied to the focus guards such
that the focus guards themselves are not accessible via swipe?

**Comment by theKashey** [comment]
Their _accesibility_ should not matter. But you have to manually test this assumption.
