### ISSUE TITLE
Can't click without scroll being changed

### ISSUE THREAD

**Issue by leads** [theKashey/react-focus-lock#254]
Hi please see this [codesandbox example](https://codesandbox.io/s/eager-frog-sdj3hf) and [demo](https://sdj3hf.csb.app/).

Here I am using a Modal we have built and it uses [body-scroll-lock-upgrade](https://github.com/rick-liruixin/body-scroll-lock-upgrade) and react-focus-lock.

If you open the Modal then scroll down the list, try clicking the label text. It will jump you back up. You can click the checkbox directly but then trying another click elsewhere it will scroll back to that focussed item.

I [made a demo without checkboxes](https://codesandbox.io/s/tender-scooby-y89gjw) and the same thing happens if you click in a grey box. Also a [demo without the body-scroll-lock](https://codesandbox.io/s/mutable-sea-jh83sj).

Hopefully this is an implementation mistake on our behalf that we have missed. Any ideas?

Thanks

**Comment by theKashey** [comment]
Root cause - you have a focusable element "above" focus lock. When you click on the "text" you are selecting this element and as it is "above" focus (or "outside") the focus will be returned to where it belongs.

The fix is simple - wrap dialog with focus-lock, not the other way around - https://codesandbox.io/s/busy-blackwell-6svn9r?file=/src/Modal.tsx

How to check: you should be able to select text with a mouse. If you cannot, then something is wrong. Focus-lock implicitly allows for focus to reside on `body`, but nowhere else.

**Comment by leads** [comment]
Awesome, thank you!
