### ISSUE TITLE
FocusLock cause popups to scroll to top

### ISSUE THREAD

**Issue by Elucidat-Tiago** [theKashey/react-focus-lock#64]
Clicking anywhere on a popup causes the first element of the popup to receive focus (even when using persistentFocus={false}) which in turn cause the popup to scroll back to the top.

Text selection inside the popup is also disabled even though persistentFocus is set to false.

https://codesandbox.io/s/m7x7qq8y19

**Comment by theKashey** [comment]
The Dialog node itself is focusable (but not tabbable). That's why it's working that way.
There are two ways to fix it:
- acquire a `ref` to Dialog, and pass as a `shard` properly to a FocusLock (does not work, ref would refer to a Component, not HTML node)
- use `whiteList` to hide Dialog node from FocusLock
```js
const whileList = el =>
  !(el.getAttribute("role") === "document" && el.tabIndex === -1);

<FocusLock
        whiteList={whileList}
>
```

See https://codesandbox.io/s/vmq598r420

PS: Keep in mind 
- MUI v3 (current) has a broken focus lock
- MUI v4 (alpha) has a working focus lock, and you dont have to use FocusLock.

**Comment by Elucidat-Tiago** [comment]
Thank you for your reply.
Yes that works, apologies, should have noticed there was a whitelist prop when I looked at the documentation.
